// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/start": {
            "post": {
                "description": "Creates anonymous user or returns existing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start onboarding / auth",
                "parameters": [
                    {
                        "description": "Onboarding data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.AuthStartInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.AuthStartOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/goals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List goals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/personas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List personas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.ProfileOutput"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "List sessions history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SessionsListOutput"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Session",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.CreateSessionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.CreateSessionOutput"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session debrief",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.FinishOutput"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/finish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Finish session and debrief",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.FinishOutput"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/messages": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Send chat message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SendMessageInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SendMessageOutput"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/suggest": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Magic wand suggestion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Draft",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SuggestInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SuggestOutput"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_elfrida_chemistry-coach_internal_domain.DailyExercise": {
            "type": "object",
            "properties": {
                "criterion": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_domain.DebriefScores": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.ScoreDetail"
                },
                "clarity": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.ScoreDetail"
                },
                "confidence": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.ScoreDetail"
                },
                "respect": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.ScoreDetail"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_domain.ImprovedReply": {
            "type": "object",
            "properties": {
                "improved": {
                    "type": "string"
                },
                "original": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_domain.RiskFlag": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "suggestion": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_domain.ScoreDetail": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_domain.SkillScores": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "clarity": {
                    "type": "integer"
                },
                "confidence": {
                    "type": "integer"
                },
                "respect": {
                    "type": "integer"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.AuthStartInput": {
            "type": "object",
            "properties": {
                "birthYear": {
                    "type": "integer"
                },
                "consents": {
                    "type": "object",
                    "properties": {
                        "agreesToRules": {
                            "type": "boolean"
                        },
                        "isAdult": {
                            "type": "boolean"
                        },
                        "understandsAI": {
                            "type": "boolean"
                        }
                    }
                },
                "userID": {
                    "description": "optional: return existing",
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.AuthStartOutput": {
            "type": "object",
            "properties": {
                "isNewUser": {
                    "type": "boolean"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.ConsentRiskDTO": {
            "type": "object",
            "properties": {
                "detected": {
                    "type": "boolean"
                },
                "explanation": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "suggestion": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.CreateSessionInput": {
            "type": "object",
            "properties": {
                "goalId": {
                    "type": "string"
                },
                "personaId": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.CreateSessionOutput": {
            "type": "object",
            "properties": {
                "goalTitle": {
                    "type": "string"
                },
                "openingMessage": {
                    "type": "string"
                },
                "personaInitials": {
                    "type": "string"
                },
                "personaTitle": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.FinishOutput": {
            "type": "object",
            "properties": {
                "finishedAt": {
                    "type": "string"
                },
                "hasRisk": {
                    "type": "boolean"
                },
                "improvedReplies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.ImprovedReply"
                    }
                },
                "persona": {
                    "type": "string"
                },
                "riskFlags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.RiskFlag"
                    }
                },
                "scenario": {
                    "type": "string"
                },
                "scores": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.DebriefScores"
                },
                "sessionId": {
                    "type": "string"
                },
                "strengths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tipForNext": {
                    "type": "string"
                },
                "weaknesses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.MessageDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusLabel": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.ProfileOutput": {
            "type": "object",
            "properties": {
                "initials": {
                    "type": "string"
                },
                "recommendedGoalId": {
                    "type": "string"
                },
                "totalSessions": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                },
                "weakestSkill": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SendMessageInput": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SendMessageOutput": {
            "type": "object",
            "properties": {
                "consentRisk": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.ConsentRiskDTO"
                },
                "messageCount": {
                    "type": "integer"
                },
                "personaMessage": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.MessageDTO"
                },
                "shouldSuggestEnd": {
                    "type": "boolean"
                },
                "userMessage": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.MessageDTO"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SessionListItem": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "hasRisk": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "persona": {
                    "type": "string"
                },
                "scenario": {
                    "type": "string"
                },
                "scores": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.SkillScores"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SessionsListOutput": {
            "type": "object",
            "properties": {
                "clarityHistory": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dailyExercise": {
                    "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_domain.DailyExercise"
                },
                "focusSessionCount": {
                    "type": "integer"
                },
                "focusSkill": {
                    "type": "string"
                },
                "focusSkillLabel": {
                    "type": "string"
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_elfrida_chemistry-coach_internal_usecase.SessionListItem"
                    }
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SuggestInput": {
            "type": "object",
            "properties": {
                "draft": {
                    "type": "string"
                }
            }
        },
        "github_com_elfrida_chemistry-coach_internal_usecase.SuggestOutput": {
            "type": "object",
            "properties": {
                "suggestion": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Alice Chemistry Coach API",
	Description:      "18+ AI-тренажёр романтической коммуникации (MVP backend)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
